import type { ToolpathSection, SbpConfig, ToolpathMove } from './types';

const FMT = 6; // decimal places for coordinates

function f(n: number): string {
  return n.toFixed(FMT);
}

/**
 * Build an OpenSBP file string from toolpath sections and config.
 * Format verified line-by-line against Aspire reference output.
 */
export function writeSBP(sections: ToolpathSection[], config: SbpConfig): string {
  const lines: string[] = [];

  // Header comments
  lines.push("'STL-TO-SBP CONVERTER");
  lines.push("'----------------------------------------------------------------");
  lines.push("'SHOPBOT ROUTER FILE IN INCHES");
  lines.push("'GENERATED BY MeshCraft STL-to-SBP");
  lines.push(
    `'Minimum extent in X = 0.000 Minimum extent in Y = 0.000 Minimum extent in Z = 0.000`,
  );
  lines.push(
    `'Maximum extent in X = ${config.materialX.toFixed(3)} Maximum extent in Y = ${config.materialY.toFixed(3)} Maximum extent in Z = ${config.materialZ.toFixed(3)}`,
  );
  lines.push(`'Length of material in X = ${(config.materialX + config.offsetX * 2).toFixed(3)}`);
  lines.push(`'Length of material in Y = ${(config.materialY + config.offsetY * 2).toFixed(3)}`);
  lines.push(`'Depth of material in Z = ${config.materialZ.toFixed(3)}`);
  lines.push("'Home Position Information = Bottom Left Corner, Table Surface ");
  lines.push(`'Home X = 0.000000 Home Y = 0.000000 Home Z = ${f(config.homeZ)}`);
  lines.push(`'Rapid clearance gap or Safe Z = ${config.safeZ.toFixed(3)}`);
  lines.push("'UNITS:Inches");
  lines.push("'");
  lines.push("IF %(25)=1 THEN GOTO UNIT_ERROR\t'check to see software is set to standard");
  lines.push("SA                             \t'Set program to absolute coordinate mode");
  lines.push('CN, 90');

  // Write each section (roughing, finishing)
  for (const section of sections) {
    const { tool, moves, name } = section;

    lines.push("'New Path");
    lines.push(`'Toolpath Name = ${name}`);
    lines.push(`'Tool Name   = ${tool.name}`);
    lines.push('');
    lines.push(`&PWSafeZ = ${config.safeZ.toFixed(3)}`);
    lines.push('&PWZorigin = Table Surface');
    lines.push(`&PWMaterial = ${config.materialZ.toFixed(3)}`);
    lines.push(`'&ToolName = "${tool.name}"`);
    lines.push(`&Tool =${tool.atcSlot}           'Tool number to change to`);
    lines.push("C9                   'Change tool");
    lines.push(`TR,${tool.cutting.rpm}               'Set spindle RPM`);
    lines.push("C6                   'Spindle on");
    lines.push('PAUSE 2');
    lines.push("'");
    lines.push(`MS,${tool.cutting.feedRate},${tool.cutting.plungeRate}`);

    // Write moves
    writeMoves(lines, moves, config);

    // End-of-section retract and spindle off
    lines.push("'");
    lines.push("'Turning router OFF");
    lines.push('C7');
  }

  // Footer
  lines.push(`J3,0.000000,0.000000,${f(config.homeZ)}`);
  lines.push("'");
  lines.push("'Turning router OFF");
  lines.push('C7');
  lines.push('END');
  lines.push("'");
  lines.push("'");
  lines.push('UNIT_ERROR:');
  lines.push("CN, 91                            'Run file explaining unit error");
  lines.push('END');

  return lines.join('\n') + '\n';
}

function writeMoves(lines: string[], moves: ToolpathMove[], config: SbpConfig): void {
  let lastType: 'rapid' | 'cut' | null = null;

  for (const move of moves) {
    if (move.type === 'rapid') {
      if (lastType === 'cut') {
        // Retract from cut to safe Z first
        lines.push(`J3,${f(move.x)},${f(move.y)},${f(config.safeZ)}`);
        if (move.z === config.safeZ) {
          lastType = move.type;
          continue;
        }
      }
      if (move.z !== config.safeZ) {
        lines.push(`JZ,${f(move.z)}`);
      }
      lines.push(`J3,${f(move.x)},${f(move.y)},${f(move.z)}`);
    } else {
      lines.push(`M3,${f(move.x)},${f(move.y)},${f(move.z)}`);
    }
    lastType = move.type;
  }

  // Final retract if ended on a cut
  if (lastType === 'cut' && moves.length > 0) {
    const last = moves[moves.length - 1];
    lines.push(`J3,${f(last.x)},${f(last.y)},${f(config.safeZ)}`);
    lines.push(`JZ,${f(config.homeZ)}`);
  }
}
